# Based on Automaton workflow by Goonstation
# Which is based on Turdis by Yogstation

name: Nightly

# Runs every evening around 8pm eastern, before the coders start breaking shit.
on:
  schedule:
    - cron: '16 23 * * *'

jobs:
  nightly:
    name: Package
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        map: ["ATLAS", "DEVTEST"]
    steps:
      - uses: actions/checkout@v3
        with:
            repository: 'goonstation/goonstation'

      - name: Cache BYOND
        uses: actions/cache@v3
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd ${{github.workspace}}
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV
          touch +secret/__secret.dme

      - name: Compile map
        run: |
          tools/ci/dm.sh -DMAP_OVERRIDE_${{matrix.map}} goonstation.dme
      
      - name: Package
        run: |
          mkdir -p packaged/goonstation/sound/
          mkdir -p packaged/goonstation/data/
          echo "extended" > packaged/goonstation/data/mode.txt
          mv sound/radio_station packaged/goonstation/sound/
          mv goonstation.dmb goonstation.rsc strings assets browserassets LICENSE rust_g.dll ./packaged/goonstation

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GoonNightly${{matrix.map}}
          path: ${{github.workspace}}/packaged
